
# file: ibert_ultrascale_gth_0.xdc
####################################################################################
##   ____  ____ 
##  /   /\/   /
## /___/  \  /    Vendor: Xilinx
## \   \   \/     Version : 2012.3
##  \   \         Application : IBERT Ultrascale
##  /   /         Filename : example_ibert_ultrascale_gth_0.xdc
## /___/   /\     
## \   \  /  \ 
##  \___\/\___\
##
##
## 
## Generated by Xilinx IBERT 7Series 
##**************************************************************************
##
## Icon Constraints
##
create_clock -name D_CLK -period 12.5 [get_ports gth_sysclkp_i]
set_clock_groups -group [get_clocks D_CLK -include_generated_clocks] -asynchronous
set_property C_CLK_INPUT_FREQ_HZ 80000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER true [get_debug_cores dbg_hub]

##gth_refclk lock constraints
##
set_property PACKAGE_PIN AF6 [get_ports gth_refclk0p_i[0]]
set_property PACKAGE_PIN AF5 [get_ports gth_refclk0n_i[0]]
set_property PACKAGE_PIN AD6 [get_ports gth_refclk1p_i[0]]
set_property PACKAGE_PIN AD5 [get_ports gth_refclk1n_i[0]]
set_property PACKAGE_PIN AB6 [get_ports gth_refclk0p_i[1]]
set_property PACKAGE_PIN AB5 [get_ports gth_refclk0n_i[1]]
set_property PACKAGE_PIN Y6 [get_ports gth_refclk1p_i[1]]
set_property PACKAGE_PIN Y5 [get_ports gth_refclk1n_i[1]]
set_property PACKAGE_PIN V6 [get_ports gth_refclk0p_i[2]]
set_property PACKAGE_PIN V5 [get_ports gth_refclk0n_i[2]]
set_property PACKAGE_PIN T6 [get_ports gth_refclk1p_i[2]]
set_property PACKAGE_PIN T5 [get_ports gth_refclk1n_i[2]]
set_property PACKAGE_PIN P6 [get_ports gth_refclk0p_i[3]]
set_property PACKAGE_PIN P5 [get_ports gth_refclk0n_i[3]]
set_property PACKAGE_PIN M6 [get_ports gth_refclk1p_i[3]]
set_property PACKAGE_PIN M5 [get_ports gth_refclk1n_i[3]]
##
## Refclk constraints
##
create_clock -name gth_refclk0_0 -period 6.25 [get_ports gth_refclk0p_i[0]]
create_clock -name gth_refclk1_0 -period 6.25 [get_ports gth_refclk1p_i[0]]
set_clock_groups -group [get_clocks gth_refclk0_0 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gth_refclk1_0 -include_generated_clocks] -asynchronous
create_clock -name gth_refclk0_1 -period 6.25 [get_ports gth_refclk0p_i[1]]
create_clock -name gth_refclk1_1 -period 6.25 [get_ports gth_refclk1p_i[1]]
set_clock_groups -group [get_clocks gth_refclk0_1 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gth_refclk1_1 -include_generated_clocks] -asynchronous
create_clock -name gth_refclk0_2 -period 6.25 [get_ports gth_refclk0p_i[2]]
create_clock -name gth_refclk1_2 -period 6.25 [get_ports gth_refclk1p_i[2]]
set_clock_groups -group [get_clocks gth_refclk0_2 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gth_refclk1_2 -include_generated_clocks] -asynchronous
create_clock -name gth_refclk0_3 -period 6.25 [get_ports gth_refclk0p_i[3]]
create_clock -name gth_refclk1_3 -period 6.25 [get_ports gth_refclk1p_i[3]]
set_clock_groups -group [get_clocks gth_refclk0_3 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gth_refclk1_3 -include_generated_clocks] -asynchronous
##
## System clock pin locs and timing constraints
##
set_property PACKAGE_PIN AK22 [get_ports gth_sysclkp_i]
set_property PACKAGE_PIN E12 [get_ports DAQ_SPY_SEL_18]
set_property IOSTANDARD  LVCMOS18   [get_ports DAQ_SPY_SEL_18]

set_property -dict { PACKAGE_PIN AK22  IOSTANDARD LVDS  DIFF_TERM_ADV TERM_100 } [get_ports gth_sysclkp_i]
set_property IOSTANDARD LVDS [get_ports gth_sysclkp_i]


set_property PACKAGE_PIN U21        [get_ports kus_dl_sel]
set_property IOSTANDARD  LVCMOS18   [get_ports kus_dl_sel]

set_property PACKAGE_PIN T23        [get_ports fpga_sel_18]
set_property IOSTANDARD  LVCMOS18   [get_ports fpga_sel_18]

set_property PACKAGE_PIN W29        [get_ports rst_clks_18_b]
set_property IOSTANDARD  LVCMOS18   [get_ports rst_clks_18_b]


set_property PACKAGE_PIN L9        [get_ports done]
set_property IOSTANDARD  LVCMOS18   [get_ports done]

set_property PACKAGE_PIN AN14       [get_ports ccb_hardrst_b]
set_property IOSTANDARD  LVCMOS18   [get_ports ccb_hardrst_b]

set_property PACKAGE_PIN AP14        [get_ports ccb_soft_rst]
set_property IOSTANDARD  LVCMOS18   [get_ports ccb_soft_rst]

set_property package_pin  K11      [get_ports RX12_I2C_ENA]
set_property IOSTANDARD   LVCMOS18 [get_ports RX12_I2C_ENA]
set_property package_pin  G12      [get_ports RX12_CS_B]
set_property IOSTANDARD   LVCMOS18 [get_ports RX12_CS_B]
set_property package_pin  F12      [get_ports RX12_RST_B]
set_property IOSTANDARD   LVCMOS18 [get_ports RX12_RST_B]


set_property package_pin  J13      [get_ports TX12_I2C_ENA]
set_property IOSTANDARD   LVCMOS18 [get_ports TX12_I2C_ENA]

set_property package_pin  G10      [get_ports TX12_CS_B]
set_property IOSTANDARD   LVCMOS18 [get_ports TX12_CS_B]
set_property package_pin  F10      [get_ports TX12_RST_B]
set_property IOSTANDARD   LVCMOS18 [get_ports TX12_RST_B]


set_property package_pin  K12      [get_ports B04_I2C_ENA]
set_property IOSTANDARD   LVCMOS18 [get_ports B04_I2C_ENA]
set_property package_pin  H11      [get_ports B04_CS_B]
set_property IOSTANDARD   LVCMOS18 [get_ports B04_CS_B]
set_property package_pin  G11      [get_ports B04_RST_B]
set_property IOSTANDARD   LVCMOS18 [get_ports B04_RST_B]

set_property BITSTREAM.CONFIG.USERID 0x0D3B7E57 [current_design]
set_property BITSTREAM.CONFIG.OVERTEMPSHUTDOWN ENABLE [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
set_property BITSTREAM.CONFIG.CONFIGFALLBACK ENABLE [current_design]
set_property BITSTREAM.CONFIG.SPI_32BIT_ADDR NO [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 8 [current_design]
set_property BITSTREAM.CONFIG.SPI_FALL_EDGE YES [current_design]
set_property BITSTREAM.CONFIG.EXTMASTERCCLK_EN div-1 [current_design]
set_property CONFIG_MODE SPIx8 [current_design]
set_property CONFIG_VOLTAGE 1.8 [current_design]
set_property CFGBVS GND [current_design]


