# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /net/top/homes/mhussain/ODMB/B2B_test/b2b_ibert_4p8_4quad/ibert_ultrascale_gth_0_ex/imports/example_ibert_ultrascale_gth_0.xdc

# XDC: /net/top/homes/mhussain/ODMB/B2B_test/b2b_ibert_4p8_4quad/ibert_ultrascale_gth_0_ex/imports/ibert_ultrascale_gth_ip_example.xdc

# IP: ip/ibert_ultrascale_gth_0/ibert_ultrascale_gth_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ibert_ultrascale_gth_0 || ORIG_REF_NAME==ibert_ultrascale_gth_0} -quiet] -quiet
