# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 5
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xcku035-ffva1156-1-c

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /net/top/homes/mhussain/ODMB/B2B_test/b2b_ibert_4p8_4quad/ibert_ultrascale_gth_0_ex/ibert_ultrascale_gth_0_ex.cache/wt [current_project]
set_property parent.project_path /net/top/homes/mhussain/ODMB/B2B_test/b2b_ibert_4p8_4quad/ibert_ultrascale_gth_0_ex/ibert_ultrascale_gth_0_ex.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /net/top/homes/mhussain/ODMB/B2B_test/b2b_ibert_4p8_4quad/ibert_ultrascale_gth_0_ex/ibert_ultrascale_gth_0_ex.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /net/top/homes/mhussain/ODMB/B2B_test/b2b_ibert_4p8_4quad/ibert_ultrascale_gth_0_ex/imports/example_ibert_ultrascale_gth_0.v
read_ip -quiet /net/top/homes/mhussain/ODMB/B2B_test/b2b_ibert_4p8_4quad/ibert_ultrascale_gth_0_ex/ibert_ultrascale_gth_0_ex.srcs/sources_1/ip/ibert_ultrascale_gth_0/ibert_ultrascale_gth_0.xci
set_property is_enabled false [get_files -all /net/top/homes/mhussain/ODMB/B2B_test/b2b_ibert_4p8_4quad/ibert_ultrascale_gth_0_ex/ibert_ultrascale_gth_0_ex.srcs/sources_1/ip/ibert_ultrascale_gth_0/data/mb_bootloop_le.elf]
set_property is_enabled false [get_files -all /net/top/homes/mhussain/ODMB/B2B_test/b2b_ibert_4p8_4quad/ibert_ultrascale_gth_0_ex/ibert_ultrascale_gth_0_ex.srcs/sources_1/ip/ibert_ultrascale_gth_0/mb_bootloop_le.elf]
set_property used_in_implementation false [get_files -all /net/top/homes/mhussain/ODMB/B2B_test/b2b_ibert_4p8_4quad/ibert_ultrascale_gth_0_ex/ibert_ultrascale_gth_0_ex.srcs/sources_1/ip/ibert_ultrascale_gth_0/synth/ibert_ultrascale_gth_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /net/top/homes/mhussain/ODMB/B2B_test/b2b_ibert_4p8_4quad/ibert_ultrascale_gth_0_ex/ibert_ultrascale_gth_0_ex.srcs/sources_1/ip/ibert_ultrascale_gth_0/synth/ibert_ultrascale_gth_0.xdc]
set_property used_in_implementation false [get_files -all /net/top/homes/mhussain/ODMB/B2B_test/b2b_ibert_4p8_4quad/ibert_ultrascale_gth_0_ex/ibert_ultrascale_gth_0_ex.srcs/sources_1/ip/ibert_ultrascale_gth_0/synth/sw_mcs_all.xdc]
set_property used_in_implementation false [get_files -all /net/top/homes/mhussain/ODMB/B2B_test/b2b_ibert_4p8_4quad/ibert_ultrascale_gth_0_ex/ibert_ultrascale_gth_0_ex.srcs/sources_1/ip/ibert_ultrascale_gth_0/synth/attributes.xdc]

read_ip -quiet /net/top/homes/mhussain/ODMB/B2B_test/b2b_ibert_4p8_4quad/ibert_ultrascale_gth_0_ex/ibert_ultrascale_gth_0_ex.srcs/sources_1/ip/vio_0/vio_0.xci
set_property used_in_implementation false [get_files -all /net/top/homes/mhussain/ODMB/B2B_test/b2b_ibert_4p8_4quad/ibert_ultrascale_gth_0_ex/ibert_ultrascale_gth_0_ex.srcs/sources_1/ip/vio_0/vio_0.xdc]
set_property used_in_implementation false [get_files -all /net/top/homes/mhussain/ODMB/B2B_test/b2b_ibert_4p8_4quad/ibert_ultrascale_gth_0_ex/ibert_ultrascale_gth_0_ex.srcs/sources_1/ip/vio_0/vio_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /net/top/homes/mhussain/ODMB/B2B_test/b2b_ibert_4p8_4quad/ibert_ultrascale_gth_0_ex/imports/example_ibert_ultrascale_gth_0.xdc
set_property used_in_implementation false [get_files /net/top/homes/mhussain/ODMB/B2B_test/b2b_ibert_4p8_4quad/ibert_ultrascale_gth_0_ex/imports/example_ibert_ultrascale_gth_0.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top example_ibert_ultrascale_gth_0 -part xcku035-ffva1156-1-c


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef example_ibert_ultrascale_gth_0.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file example_ibert_ultrascale_gth_0_utilization_synth.rpt -pb example_ibert_ultrascale_gth_0_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
